### PR TITLE
Update Partytown to 0.8.0

### PR DESCRIPTION
**Pull request by miina**
Updates the included Partytown lib to the latest versiomn (0.8.0).

### CODE REVIEW

**Comment by miina** [comment]
Hey @thelovekesh, added this PR to upgrade the included Partytown plugin.

**Comment by thelovekesh** [comment]
Thanks, @miina! LGTM, merging now 🚀

**Review by thelovekesh — APPROVED** [review]

**Comment by thelovekesh** [comment]
@miina We Need to bump the version in `package.json`, could be a part of the same PR?

**Comment by miina** [comment]
@thelovekesh Good point, updated here together with the lock file: [410c447](https://github.com/rtCamp/wp-partytown/pull/8/commits/410c447c0c4b2b38ee1263c2f79834cccc535d67).

**Review by thelovekesh — APPROVED** [review]

**Pull request merged**
